-- Staging zone of an import (ADR-0004): what was read from a statement,
-- before the operator confirms it. Identifiers are generated by the program,
-- so the same SQL works in SQLite and PostgreSQL.

CREATE TABLE import_batch (
    id VARCHAR(36) PRIMARY KEY,
    created_at VARCHAR(40) NOT NULL,
    statement_file VARCHAR(255) NOT NULL,
    curriculum_file VARCHAR(255),
    students INTEGER NOT NULL,
    subjects INTEGER NOT NULL
);

CREATE TABLE import_result (
    batch_id VARCHAR(36) NOT NULL REFERENCES import_batch (id),
    student VARCHAR(255) NOT NULL,
    label VARCHAR(600) NOT NULL,
    grade VARCHAR(40),
    PRIMARY KEY (batch_id, student, label)
);

CREATE TABLE import_check (
    batch_id VARCHAR(36) NOT NULL REFERENCES import_batch (id),
    label VARCHAR(600) NOT NULL,
    settled VARCHAR(600) NOT NULL,
    source VARCHAR(40) NOT NULL,
    notes VARCHAR(2000) NOT NULL,
    PRIMARY KEY (batch_id, label)
);
